In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Load dataset
path = 'train.csv'
event_path = 'events_train.csv'

match_data = pd.read_csv(path)
events_data = pd.read_csv(event_path)

In [5]:
match_data.tail()

,match_id,match_date,kick_off,home_score,away_score,match_week,home_team.home_team_name,away_team.away_team_name,stadium.name,referee.name,home_team.managers_name,home_team.managers_country,home_team.managers_dob,away_team.managers_name,away_team.managers_country,away_team.managers_dob,Poss,Result
80,3773415,2021-02-21,14:00:00.000,1,1,24,Barcelona,Cádiz,Spotify Camp Nou,Juan Martínez Munuera,Ronald Koeman,Netherlands,1963-03-21,Álvaro Cervera Díaz,Spain,1965-09-20,19.0,Draw
81,3764440,2021-02-24,19:00:00.000,3,0,1,Barcelona,Elche,Spotify Camp Nou,Isidro Díaz de Mera Escuderos,Ronald Koeman,Netherlands,1963-03-21,Francisco Escriba Segura,Spain,1965-05-03,35.0,Win
82,3773665,2021-03-06,21:00:00.000,0,2,26,Osasuna,Barcelona,Estadio El Sadar,Guillermo Cuadra Fernández,Jagoba Arrasate Elustondo,Spain,1978-04-22,Ronald Koeman,Netherlands,1963-03-21,63.0,Lose
83,3773369,2021-03-15,21:00:00.000,4,1,27,Barcelona,Huesca,Spotify Camp Nou,Adrián Cordero Vega,Ronald Koeman,Netherlands,1963-03-21,Juan José Rojo Martín,Spain,1968-03-23,31.0,Win
84,3773586,2021-04-29,19:00:00.000,1,2,33,Barcelona,Granada,Spotify Camp Nou,Pablo González Fuertes,Ronald Koeman,Netherlands,1963-03-21,Diego Martínez Penas,Spain,1980-12-16,19.0,Lose

In [6]:
events_data.tail()

,id,index,period,timestamp,possession,duration,type.name,possession_team.name,play_pattern.name,team.name,...,goalkeeper.shot_saved_to_post,goalkeeper.lost_out,foul_committed.penalty,foul_won.penalty,goalkeeper.success_in_play,block.save_block,shot.follows_dribble,goalkeeper.success_out,player_off.permanent,goalkeeper.lost_in_play
328670,5491f041-8e91-4d81-a698-148684af52ef,4032,2,00:47:56.685,224,1.46939,Pass,Osasuna,Regular Play,Barcelona,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328671,533193c4-fd30-496c-b8fb-865664e11082,4033,2,00:47:58.155,224,NaN,Ball Receipt*,Osasuna,Regular Play,Barcelona,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328672,a6c939dd-6a8e-4683-8c96-96850322752f,4034,2,00:47:58.155,224,0.00000,Clearance,Osasuna,Regular Play,Osasuna,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328673,37a300ed-f542-485c-a3c8-7f1c7e3969ff,4035,2,00:48:02.016,224,0.00000,Half End,Osasuna,Regular Play,Osasuna,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328674,659ab26c-7ac3-41d9-a69f-7f25901c8eab,4036,2,00:48:02.016,224,0.00000,Half End,Osasuna,Regular Play,Barcelona,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN